# Generated by Django 5.1.4 on 2026-06-27 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_autorite', models.CharField(choices=[('pompiers', 'Pompiers (Sapeurs-Pompiers)'), ('police', 'Police / Gendarmerie'), ('sante', 'SAMU / Santé'), ('senelec', 'SENELEC (Électricité)'), ('onas', 'ONAS (Inondations)')], max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('nom_service', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
