# Generated by Django 6.0.6 on 2026-06-09 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(choices=[('accident', 'Accident'), ('inondation', 'Inondation'), ('incendie', 'Incendie'), ('electricite', 'Coupure electricite'), ('insecurite', 'Insecurite'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thies'), ('saint_louis', 'Saint-Louis'), ('kaolack', 'Kaolack'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('diourbel', 'Diourbel'), ('kaffrine', 'Kaffrine'), ('sedhiou', 'Sedhiou'), ('kedougou', 'Kedougou')], max_length=50)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('resolu', 'Resolu')], default='nouveau', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('citoyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
